FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip

COPY backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ingestion_jobs /app/ingestion_jobs

CMD ["python", "-m", "ingestion_jobs.daily_ingestion"]
