# backend/ingestion_jobs/docker/Dockerfile.task_generator
FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip

COPY ../../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY .. /app/ingestion_jobs

CMD ["python", "-m", "ingestion_jobs.recall_task_generator"]
