// frontend/tests/dashboard.spec.ts
import { test, expect } from '@playwright/test';

test.describe('Aegis Command Console E2E Matrix', () => {

  test.beforeEach(async ({ page }) => {
    // Intercept the global metrics call on application mount to guarantee deterministic layout data
    await page.route('**/api/metrics/global', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          total_vins: 25041,
          fleet_health_index: 91.2
        })
      });
    });

    // Point this directly to your local Vite application dev server environment context
    await page.goto('http://localhost:5173');
  });

  test('should mount cleanly and populate dashboard telemetry values from the backend', async ({ page }) => {
    const dbMatrixCounter = page.locator('text=25,041');
    const healthThreshold = page.locator('text=91.2%');

    await expect(dbMatrixCounter).toBeVisible();
    await expect(healthThreshold).toBeVisible();
  });

  test('should evaluate a clean telemetry pass if a free manifest under the 10-VIN limit is dropped', async ({ page }) => {
    // Intercept the query router lookups for individual vehicles to return deterministic mocks
    await page.route('**/api/recalls*', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify([]) // Emulating zero threats returned
      });
    });

    // Emulate typing a valid free sandbox payload inside the manual input console loop
    const textarea = page.locator('textarea[placeholder*="Manual String Override Input Loop"]');
    await textarea.fill([
      'FORD, TRANSIT-250, 2022',
      'CHEVROLET, BOLT EV, 2021',
      'TOYOTA, PRIUS, 2020'
    ].join('\n'));

    // Fire the calculation sweep
    await page.click('button:has-text("Run Safety Threat Sweep")');

    // Confirm the clean sweep success banner alerts your user cleanly
    const successBanner = page.locator('text=Scan Complete: Clean telemetry across all targeted assets.');
    await expect(successBanner).toBeVisible();
  });

  test('should trigger the premium glassmorphism paywall popup modal when an 11-car bulk manifest is submitted', async ({ page }) => {
    const textarea = page.locator('textarea[placeholder*="Manual String Override Input Loop"]');
    
    // Construct a payload containing exactly 11 items to breach the 10-VIN freemium barrier
    const premiumPayload = Array.from({ length: 11 }, (_, i) => `FORD, TRANSIT, ${2010 + (i % 15)}`).join('\n');
    await textarea.fill(premiumPayload);

    await page.click('button:has-text("Run Safety Threat Sweep")');

    // Verify the paywall intercept shield triggers immediately
    const upgradeModalHeader = page.locator('text=Activate Core Protection');
    await expect(upgradeModalHeader).toBeVisible();

    // Verify that the count logic targets the blocked rows string count exactly
    await expect(page.locator('text=11 active rows')).toBeVisible();

    // Verify the monetization formula match calculations: Base $99 + (11 assets * $2.50) = $126.50
    // Note: If you haven't declared calculateCustomMRR in this file or imported it, 
    // Playwright matches the plain text generated by the client component layout.
    const customQuoteDisplay = page.locator('text=$126.50');
    const breakdownBreakdown = page.locator('text=Active Monitoring Asset Allocation (11 units × $2.50)');

    await expect(customQuoteDisplay).toBeVisible();
    await expect(breakdownBreakdown).toBeVisible();
  });

  test('should allow a user to dismiss the pricing modal to adjust their fleet list size constraints', async ({ page }) => {
    const textarea = page.locator('textarea[placeholder*="Manual String Override Input Loop"]');
    const premiumPayload = Array.from({ length: 12 }, () => 'CHEVROLET, BOLT EV, 2021').join('\n');
    
    await textarea.fill(premiumPayload);
    await page.click('button:has-text("Run Safety Threat Sweep")');

    // Modal pops up
    const modal = page.locator('text=Activate Core Protection');
    await expect(modal).toBeVisible();

    // Dismiss via the "Adjust" action button
    await page.click('button:has-text("Adjust")');

    // Confirm that control context is passed back out gracefully to the primary workspace view
    await expect(modal).not.toBeVisible();
  });
});