from typing import Dict, Any, List
from google.cloud import firestore

db = firestore.Client()

def compute_global_metrics() -> Dict[str, Any]:
    """
    Compute global metrics across all real records ingested in recall_results.
    Returns a dict explicitly optimized for the Next.js header element.
    """
    # Query your true production results data collection
    results_ref = db.collection("recall_results")
    
    # Efficiently gather count snapshots directly from the database engine
    total_vins = list(results_ref.count().get())[0][0].value
    
    if total_vins == 0:
        return {
            "total_vins": 0,
            "processed_vins": 0,
            "failed_vins": 0,
            "pending_vins": 0,
            "total_recalls": 0,
            "high_risk_vehicles": 0,
            "average_risk_score": 0.0,
            "average_processing_time_ms": 0.0,
            "fleet_health_index": 100.0,
        }

    # Fetch records to compile aggregated attributes
    results_docs = list(results_ref.stream())
    
    processed_vins = 0
    failed_vins = 0
    pending_vins = 0
    total_recalls = 0
    high_risk_vehicles = 0

    risk_scores: List[float] = []
    
    for doc in results_docs:
        data = doc.to_dict() or {}
        
        status = data.get("status", "completed")
        # Extract nested structures inside the 'result' map generated by the worker
        result_payload = data.get("result") or {}
        recalls_list = result_payload.get("results") or []
        
        # Status counts matching your operational parameters
        if status == "completed" or status == "processed":
            processed_vins += 1
        elif status in ["failed_api", "failed_json", "failed_format", "failed"]:
            failed_vins += 1
        else:
            pending_vins += 1

        # Total recalls discovered across your datasets
        num_recalls = len(recalls_list)
        total_recalls += num_recalls

        # Calculate a deterministic risk score for the vehicle profile based on active count
        # (MVP business rule logic: 25 points per recall, capped at a maximum ceiling of 100)
        calculated_risk = min(100.0, num_recalls * 25.0)
        risk_scores.append(calculated_risk)
        
        if calculated_risk >= 75.0:
            high_risk_vehicles += 1

    # Compile averages
    average_risk_score = sum(risk_scores) / len(risk_scores) if risk_scores else 0.0
    fleet_health_index = max(0.0, min(100.0, 100.0 - average_risk_score))

    return {
        "total_vins": total_vins,
        "processed_vins": processed_vins,
        "failed_vins": failed_vins,
        "pending_vins": pending_vins,
        "total_recalls": total_recalls,
        "high_risk_vehicles": high_risk_vehicles,
        "average_risk_score": round(average_risk_score, 1),
        "average_processing_time_ms": 0.0,  # Legacy field placeholder for format schema protection
        "fleet_health_index": round(fleet_health_index, 1),
    }