steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/ai-safety-recall-system/recall/make-model-job',
      '.'
    ]

images:
  - 'us-central1-docker.pkg.dev/ai-safety-recall-system/recall/make-model-job'
