steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/recall/vin-batch-job",
        "-f",
        "backend/ingestion_jobs/docker/Dockerfile",
        "."
      ]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/recall/vin-batch-job"
